# Official MySQL Image
FROM mysql:latest

# Environment variables
ENV MYSQL_DATABASE=lots2do-be \
    MYSQL_USER=admin \
    MYSQL_PASSWORD=HumberR0cks! \
    MYSQL_ROOT_PASSWORD=HumberR0cks!

# Copy MySQL custom configuration file
# COPY mysql-custom.cnf /etc/mysql/conf.d/mysql-custom.cnf

# Expose port 3306
EXPOSE 3306