apiVersion: apps/v1
kind: Deployment
metadata:
  name: lots2do-be-deploy
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: lots2do-be
  template:
    metadata:
      labels:
        app: lots2do-be
    spec:
      containers:
      - name: lots2do-be
        image: jimtosinhumber/lots2do-be:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: HumberROcks!