apiVersion: v1
kind: Service
metadata:
  name: lots2do-fe
spec:
  type: NodePort
  selector:
    app: lots2do-fe
  ports:
    - protocol: TCP
      port: 80         # Port exposed by the service
      targetPort: 8000 # Port for lots2do-fe