apiVersion: v1
kind: Service
metadata:
  name: lots2do-be
spec:
  type: ClusterIP
  selector:
    app: lots2do-be
  ports:
    - protocol: TCP
      port: 3306       # Port exposed by the service
      targetPort: 3306 # Port for lots2do-be