project: default
source:
  repoURL: 'https://github.com/jimtosin-humber/devops-project2'
  path: k8s-helm
  targetRevision: HEAD
  helm:
    valueFiles:
      - values.yaml
destination:
  server: 'https://kubernetes.default.svc'
  namespace: default
syncPolicy:
  automated:
    prune: true
    selfHeal: true