name: Deploy to DockerHub
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: self-hosted # Test again

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push frontend image
        working-directory: docker/frontend
        run: |
          docker build -t jimtosinhumber/lots2do-fe .
          docker push jimtosinhumber/lots2do-fe:1.0

      - name: Build and push backend image
        working-directory: docker/backend
        run: |
          docker build -t jimtosinhumber/lots2do-be .
          docker push jimtosinhumber/lots2do-be:1.0